Varvara/feature/navigation
Simple2B/TenKabel_fe pull request #1
Opened 2023-04-26 20:01 UTC by varvarashcherbyna7

2023-04-27 06:13 UTC, StoliarskyiKostiantyn approved these changes

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on App.tsx
> +  // }
needed?

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on src/components/WrapperRegistrationLogin.tsx
> +});
You going to keep styles in component files? or maybe better move them to separate file?

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on src/components/common/btn/Btn.tsx
> +  textBtn: any;
is there better way to do this?

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on src/screens/LogIn.tsx
> +// import palette from '../assets/palette';
needed?

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on src/screens/LogIn.tsx
> +// const styles = StyleSheet.create({});
same

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on src/screens/Registration.tsx
> +// import palette from '../assets/palette';
needed?

2023-04-27 06:13 UTC, StoliarskyiKostiantyn commented on src/screens/Registration.tsx
> +// const styles = StyleSheet.create({});
same

2023-04-28 08:45 UTC, Taraslysak requested changes

2023-04-28 08:45 UTC, Taraslysak commented on src/screens/WelcomeTenKabel.tsx
> +const testDataProfession = [
What id type of `testDataProfession` ?

2023-04-28 09:05 UTC, varvarashcherbyna7 commented on src/assets/images.ts
> +  name3: require('./images/profession/name3.png'),
.) I will change this, thanks

2023-04-28 09:09 UTC, varvarashcherbyna7 commented on src/screens/WelcomeTenKabel.tsx
> +const testDataProfession = [
Thanks for the comments, it is very important for me!) I will fix everything according to the recommendations

2023-04-28 09:09 UTC, varvarashcherbyna7 commented on src/screens/Registration.tsx
> +// const styles = StyleSheet.create({});
Thanks for the comments) I will fix everything according to the recommendations

2023-05-01 06:39 UTC, merged